---
apiVersion: v1
kind: Service
metadata:
  name: {{ lower .Values.name }}-service
spec:
  selector:
    app: {{ lower .Values.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer